#!/bin/sh

# Ensure archive has no modifications
git diff --exit-code
b=$?
if [ $b = 1 ]; then
   printf "[address-warnings] archive has already modifications; not trying to fix it\n"
   exit 1
fi

# First script
fixerdir=../META/UPGRADING-SCRIPTS
for fixermsg in `ls $fixerdir/*.msg`; do
  fixer=$fixerdir/`basename $fixermsg .msg`
  $fixer log
  git diff --exit-code
  b=$?
  if [ $b = 0 ]; then
      printf "[address-warnings] fixing tool %s has nothing to fix\n" $fixer
  else
    printf "[address-warnings] rerunning after fixing\n"
    make clean
    make -j4
    a=$?
    if [ $a != 0 ]; then
      printf "[address-warnings] fixing failed\n"
      exit 1
    else
      printf "[address-warnings] committing a fix\n"
      git ci -F $fixerdir/$fixermsg .
      exit 2
    fi
  fi
done
