#!/bin/sh

if [ $# != 2 -a $# != 3 ]; then printf "Usage: make-opam-packages opam-coq-archive-root major.median.minor [package]\n"; exit 1; fi
opamarchivedir=$1
contribroot=`pwd`
version=$2
case $version in
    [89].[0123456789].[0123456789] | [89].[0123456789][0123456789].[0123456789])
        major=`echo $version | cut -d. -f 1`
        median=`echo $version | cut -d. -f 2`
        minor=`echo $version | cut -d. -f 3`
        ;;
    *)
        printf "Ill-formed version number %s\n" $version
        exit 1
esac
versiontag=v$version
mediannext=`expr $median + 1`
metadir="$( cd "$( dirname "$0" )" && pwd)"
extract=$metadir/extract-opam-description-fields 

cd $contribroot

if [ $# = 2 ]; then
  list=`cd $contribroot; ls */description | cut -d/ -f 1`
else
  list=$3
fi

for i in $list; do

  if [ $i = "atbr" ]; then echo "$i maintained on Coq community by @palmskog"; continue; fi
  if [ $i = "huffman" ]; then echo "$i maintained on Coq community by @palmskog"; continue; fi
  if [ $i = "arith-stern-brocot" ]; then echo "$i maintained on Coq community by @palmskog"; continue; fi

  printf "Building $opamarchivedir/released/packages/coq-$i/coq-$i.$version\n"
  # Extract data from description file
  descrfile=$contribroot/$i/description
  status=`grep "^Status: " $descrfile | sed -e "s/Status: *\(.*\) */\1/"`
  if [ "$status" = "Unmaintained" ]; then
    printf "Unmaintained, skipping\n"
  else
    if [ -f $contribroot/$i/LICENSE ]; then
      if `grep -iq "GNU LESSER GENERAL PUBLIC LICENSE" $contribroot/$i/LICENSE`; then
        license=`egrep "Version [1-3]" $contribroot/$i/LICENSE | sed -e "s/.*Version \([1-3\.]*\).*/ \1/"`
        license="LGPL$license"
      else
        license=""
      fi
    else
      license=""
    fi
    installdir=""
    # Heuristic to find installation directory
    # If more than one -R, we shall use the official name of the contrib
    if [ -f $contribroot/$i/Make ]; then
      nr=`grep "^-R ." $contribroot/$i/Make | wc -l`
      if [ $nr = 1 ]; then
        installdir=`grep "^-R " $contribroot/$i/Make | sed -e "s/-R *[^ ]* *\(.*\)/\1/"`
      fi
    else
      if [ -f $contribroot/$i/_CoqProject ]; then
        nr=`grep "^-R ." $contribroot/$i/_CoqProject | wc -l`
        if [ $nr = 1 ]; then
          installdir=`grep "^-R " $contribroot/$i/_CoqProject | sed -e "s/-R *[^ ]* *\(.*\)/\1/"`
        fi
      fi
    fi
    cd $opamarchivedir/released/packages
    cd coq-$i
    mkdir -p coq-$i.$version
    cd coq-$i.$version
    # Find repository
    repository=`cd $contribroot/$i; git remote -v | grep origin | grep fetch | sed -e s"@.*https://github.com/\(.*\)/$i.git.*@\1@"`
    # Create package signature
    badmd5=`echo "404: Not Found" | md5`
    url=https://github.com/$repository/$i/archive/$versiontag.tar.gz
    md5=`curl -s -L $url | md5`
    if [ $md5 = $badmd5 ]; then
      echo WARNING: RELEASE NOT FOUND
    else
      # Build opam descr and url files
      if [ "$license" = "" ]; then
          $extract $descrfile $repository/$i $major $median $url $md5 "$installdir"
      else
          $extract $descrfile $repository/$i $major $median $url $md5 "$installdir" "$license"
      fi
    fi
  fi
done
